const sb=supabase.createClient('https://hogbjrbaeedlyglegjle.supabase.co','sb_publishable_NWG23rPztabdaFhEyNtN5w_rrCeMTC5',{auth:{persistSession:true,autoRefreshToken:true}});
let pre=[],members=[],houses=[];const $=id=>document.getElementById(id);
const meta={Pegaso:['#e9e4d5','♢'],Cronos:['#4c91ff','◷'],Fénix:['#e0bd67','ϟ'],Argos:['#55c98b','◉'],Olimpo:['#ef646e','△']};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
async function authorized(){const{data}=await sb.rpc('is_directiva');return data===true}
async function load(){const[p,m,h,a]=await Promise.all([sb.from('pre_registros').select('*').order('fecha_registro',{ascending:false}),sb.from('integrantes').select('*').order('fecha_aprobacion',{ascending:false}),sb.from('casas').select('*').order('puntos',{ascending:false}),sb.from('actividades').select('*').order('fecha',{ascending:true})]);if(p.error||m.error||h.error||a.error)throw new Error((p.error||m.error||h.error||a.error).message);pre=p.data||[];members=m.data||[];houses=h.data||[];activities=a.data||[];render()}
function render(){const pending=pre.filter(x=>x.estado==='pendiente').length,approved=pre.filter(x=>x.estado==='aprobado').length,active=members.filter(x=>x.activo).length;
$('stats').innerHTML=[['✦','Pre-registros',pre.length,'de 200 cupos'],['◌','Pendientes',pending,'por revisar'],['✓','Aprobados',approved,'listos para NOVA'],['♙','Integrantes activos',active,'comunidad actual']].map(x=>`<div class="stat"><div class="stat-icon">${x[0]}</div><span>${x[1]}</span><b>${x[2]}</b><small>${x[3]}</small></div>`).join('');
$('pendingDot').classList.toggle('on',pending>0);renderChart();renderPre();renderMembers();renderHouses();renderRanking();renderNext();renderActivities()}
function renderChart(){const d=[];for(let i=13;i>=0;i--){const x=new Date();x.setHours(0,0,0,0);x.setDate(x.getDate()-i);d.push(x)}const v=d.map(x=>{const n=new Date(x);n.setDate(n.getDate()+1);return pre.filter(r=>{const z=new Date(r.fecha_registro);return z>=x&&z<n}).length});const max=Math.max(4,...v),sx=830/(v.length-1),y=n=>275-n/max*225,pts=v.map((n,i)=>`${35+i*sx},${y(n)}`).join(' ');const area=`35,275 ${pts} 865,275`;$('chart').innerHTML=`<defs><linearGradient id="chartFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#269cff" stop-opacity=".28"/><stop offset="1" stop-color="#269cff" stop-opacity="0"/></linearGradient></defs><path d="M ${area}" fill="url(#chartFill)"/><line x1="35" y1="275" x2="865" y2="275" stroke="#203149"/><polyline points="${pts}" fill="none" stroke="#48aaff" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>${v.map((n,i)=>`<circle cx="${35+i*sx}" cy="${y(n)}" r="${n?4:2}" fill="#07101c" stroke="#6dc2ff" stroke-width="2"/>`).join('')}${d.map((x,i)=>`<text x="${35+i*sx}" y="300" text-anchor="middle" fill="#536985" font-size="9">${x.getDate()}/${x.getMonth()+1}</text>`).join('')}` }
function renderNext(){const upcoming=activities.filter(a=>a.estado!=='Finalizada').slice(0,3);$('nextActivities').innerHTML=upcoming.length?upcoming.map(a=>{const d=a.fecha?new Date(a.fecha+'T00:00:00'):null;return `<div class="agenda-item"><div class="agenda-date"><b>${d?d.getDate():'—'}</b>${d?d.toLocaleDateString('es-DO',{month:'short'}).toUpperCase():''}</div><div><h4>${esc(a.nombre)}</h4><p>${esc(a.descripcion||a.tipo||'Actividad NOVA')}</p></div></div>`}).join(''):'<div class="empty">No hay actividades próximas.</div>'}
function renderActivities(){const list=[...activities];$('activityList').innerHTML=list.length?list.map(a=>{const d=a.fecha?new Date(a.fecha+'T00:00:00'):null;const cls=a.estado==='Finalizada'?'gold':a.estado==='En curso'?'blue':'';return `<article class="activity"><span class="activity-tag ${cls}">${esc(a.tipo||'ACTIVIDAD')}</span><div class="activity-icon">◇</div><h3>${esc(a.nombre)}</h3><p>${esc(a.descripcion||'Sin descripción.')}</p><div class="activity-foot"><span class="activity-meta">${d?d.toLocaleDateString('es-DO',{day:'2-digit',month:'long'}):'Sin fecha'} · <span class="activity-status">${esc(a.estado)}</span></span><b>${esc(a.tipo||'NOVA')}</b></div><button class="delete-activity" onclick="deleteActivity('${a.id}')">Eliminar actividad</button></article>`}).join(''):'<div class="activity-empty">Aún no hay actividades creadas.<br>Usa <b>+ Nueva actividad</b> para agregar la primera.</div>'}
function renderPre(){const q=($('preSearch').value||'').toLowerCase();const rows=pre.filter(x=>[x.nombre_completo,x.email,x.curso,x.seccion,x.estado].join(' ').toLowerCase().includes(q));$('preCount').textContent=`${rows.length} REGISTROS`;$('preList').innerHTML=rows.map(x=>`<div class="row"><div><b>${esc(x.nombre_completo)}</b><small>${esc(x.email)}</small></div><div>${esc(x.curso)} · ${esc(x.seccion)}</div><div><span class="status ${esc(x.estado)}">${esc(x.estado)}</span></div><div>${x.estado==='pendiente'?'<button class="action" onclick="act(\''+x.id+'\',\'aprobar_pre_registro\')">Aprobar</button><button class="action reject" onclick="act(\''+x.id+'\',\'rechazar_pre_registro\')">Rechazar</button>':'—'}</div></div>`).join('')||'<div class="empty">No encontramos solicitudes con esa búsqueda.</div>'}
function renderMembers(){const q=($('memberSearch').value||'').toLowerCase();const rows=members.filter(x=>[x.nombre_completo,x.username,x.curso,x.seccion].join(' ').toLowerCase().includes(q));$('memberCount').textContent=`${rows.length} INTEGRANTES`;$('memberList').innerHTML=rows.map(x=>{const h=houses.find(h=>h.id===x.casa_id);return `<div class="row"><div><b>${esc(x.nombre_completo)}</b><small>${esc(x.email)}</small></div><div>${esc(x.username||'Sin usuario')}</div><div>${esc(x.curso)} · ${esc(x.seccion)}</div><div><span class="status aprobado">${esc(h?.nombre||'Sin casa')}</span></div></div>`}).join('')||'<div class="empty">No hay integrantes para mostrar.</div>'}
function renderHouses(){const max=Math.max(1,...houses.map(x=>x.puntos||0));$('houseGrid').innerHTML=houses.map((h,i)=>{const m=meta[h.nombre]||['#aaa','✦'];return `<article class="house" style="--house-color:${m[0]};--house-glow:${m[0]}22"><div class="house-symbol">${m[1]}</div><h3>${esc(h.nombre)}</h3><div class="points">${h.puntos||0}</div><small>PUNTOS · POSICIÓN #${i+1}</small><div class="mini"><i style="width:${Math.max(5,(h.puntos||0)/max*100)}%"></i></div><div class="house-actions"><button onclick="points('${h.id}',-5)">−5</button><button onclick="points('${h.id}',5)">+5</button><button onclick="points('${h.id}',10)">+10</button></div></article>`}).join('')}
function renderRanking(){const max=Math.max(1,...houses.map(x=>x.puntos||0));$('ranking').innerHTML=houses.map((h,i)=>{const m=meta[h.nombre]||['#aaa','✦'];return `<div class="rank"><div class="rank-top"><span>#${i+1}</span><span>EN VIVO</span></div><div class="rank-symbol" style="color:${m[0]}">${m[1]}</div><h4>${esc(h.nombre)}</h4><b>${h.puntos||0}</b> <small>pts</small><div class="bar"><i style="width:${Math.max(5,(h.puntos||0)/max*100)}%;background:${m[0]}"></i></div></div>`}).join('')}
window.act=async(id,fn)=>{const{error}=await sb.rpc(fn,{p_pre_registro_id:id});if(error)return showToast(error.message);await load();showToast('Solicitud actualizada. ✦')}
window.points=async(id,n)=>{const{error}=await sb.rpc('agregar_puntos_casa',{p_casa_id:id,p_cantidad:n});if(error)return showToast(error.message);await load();showToast(`Puntos actualizados: ${n>0?'+':''}${n} ✦`)}
window.deleteActivity=async(id)=>{if(!confirm('¿Eliminar esta actividad?'))return;const{error}=await sb.from('actividades').delete().eq('id',id);if(error)return showToast(error.message);await load();showToast('Actividad eliminada. ✦')}
function showToast(msg){const old=document.querySelector('.toast');if(old)old.remove();const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2600)}
$('loginBtn').onclick=async()=>{const{error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error){$('msg').textContent='Correo o contraseña incorrectos.';return}if(!(await authorized())){await sb.auth.signOut();$('msg').textContent='Este usuario no tiene autorización de Directiva.';return}$('login').hidden=true;$('dashboard').hidden=false;await load()}
$('logout').onclick=async()=>{await sb.auth.signOut();location.reload()}
document.querySelectorAll('.nav-item[data-section]').forEach(b=>b.onclick=()=>{document.querySelectorAll('main section').forEach(s=>s.hidden=true);$(b.dataset.section).hidden=false;document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));b.classList.add('active');$('pageTitle').textContent={inicio:'Bienvenida, Directiva',preregistros:'Gestión de pre-registros',integrantes:'Comunidad NOVA',actividades:'Calendario NOVA',casas:'Las cinco Casas'}[b.dataset.section]})
$('preSearch').oninput=renderPre;$('memberSearch').oninput=renderMembers;
$('addActivityBtn').onclick=()=>{$('activityForm').hidden=!$('activityForm').hidden};
$('cancelActivity').onclick=()=>{$('activityForm').hidden=true};
$('saveActivity').onclick=async()=>{const nombre=$('activityName').value.trim(),tipo=$('activityType').value.trim()||'Actividad',fecha=$('activityDate').value||null,estado=$('activityStatus').value,descripcion=$('activityDescription').value.trim()||null;if(!nombre)return showToast('Escribe el nombre de la actividad.');const{data:{user}}=await sb.auth.getUser();const{error}=await sb.from('actividades').insert({nombre,tipo,fecha,estado,descripcion,creador:user?.id||null});if(error)return showToast(error.message);['activityName','activityType','activityDate','activityDescription'].forEach(id=>$(id).value='');$('activityStatus').value='Próxima';$('activityForm').hidden=true;await load();showToast('Actividad creada. ✦')};